# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
#      by: pyside-uic 0.2.13 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(483, 436)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stack_widget = QtGui.QStackedWidget(Dialog)
        self.stack_widget.setObjectName("stack_widget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtGui.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.version_name_label = QtGui.QLabel(self.page)
        self.version_name_label.setObjectName("version_name_label")
        self.horizontalLayout.addWidget(self.version_name_label)
        self.version_name = QtGui.QLineEdit(self.page)
        self.version_name.setObjectName("version_name")
        self.horizontalLayout.addWidget(self.version_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.context_widget = ContextWidget(self.page)
        self.context_widget.setObjectName("context_widget")
        self.verticalLayout.addWidget(self.context_widget)
        self.spacer_label = QtGui.QLabel(self.page)
        self.spacer_label.setText("")
        self.spacer_label.setObjectName("spacer_label")
        self.verticalLayout.addWidget(self.spacer_label)
        self.description_label = QtGui.QLabel(self.page)
        self.description_label.setObjectName("description_label")
        self.verticalLayout.addWidget(self.description_label)
        self.description = QtGui.QTextEdit(self.page)
        self.description.setObjectName("description")
        self.verticalLayout.addWidget(self.description)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_range = QtGui.QLabel(self.page)
        self.frame_range.setObjectName("frame_range")
        self.horizontalLayout_4.addWidget(self.frame_range)
        self.start_frame = QtGui.QLineEdit(self.page)
        self.start_frame.setMaximumSize(QtCore.QSize(40, 16777215))
        self.start_frame.setObjectName("start_frame")
        self.horizontalLayout_4.addWidget(self.start_frame)
        self.frame_range_to = QtGui.QLabel(self.page)
        self.frame_range_to.setObjectName("frame_range_to")
        self.horizontalLayout_4.addWidget(self.frame_range_to)
        self.end_frame = QtGui.QLineEdit(self.page)
        self.end_frame.setMaximumSize(QtCore.QSize(40, 16777215))
        self.end_frame.setObjectName("end_frame")
        self.horizontalLayout_4.addWidget(self.end_frame)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.playlists = QtGui.QComboBox(self.page)
        self.playlists.setObjectName("playlists")
        self.horizontalLayout_4.addWidget(self.playlists)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.burnin_groupbox = QtGui.QGroupBox(self.page)
        self.burnin_groupbox.setCheckable(True)
        self.burnin_groupbox.setObjectName("burnin_groupbox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.burnin_groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.username_checkbox = QtGui.QCheckBox(self.burnin_groupbox)
        self.username_checkbox.setChecked(True)
        self.username_checkbox.setObjectName("username_checkbox")
        self.horizontalLayout_5.addWidget(self.username_checkbox)
        self.date_checkbox = QtGui.QCheckBox(self.burnin_groupbox)
        self.date_checkbox.setChecked(True)
        self.date_checkbox.setObjectName("date_checkbox")
        self.horizontalLayout_5.addWidget(self.date_checkbox)
        self.shotinfo_checkbox = QtGui.QCheckBox(self.burnin_groupbox)
        self.shotinfo_checkbox.setChecked(True)
        self.shotinfo_checkbox.setObjectName("shotinfo_checkbox")
        self.horizontalLayout_5.addWidget(self.shotinfo_checkbox)
        self.frames_checkbox = QtGui.QCheckBox(self.burnin_groupbox)
        self.frames_checkbox.setChecked(True)
        self.frames_checkbox.setObjectName("frames_checkbox")
        self.horizontalLayout_5.addWidget(self.frames_checkbox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtGui.QLabel(self.burnin_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.fontsize_spinbox = QtGui.QSpinBox(self.burnin_groupbox)
        self.fontsize_spinbox.setMinimum(18)
        self.fontsize_spinbox.setMaximum(100)
        self.fontsize_spinbox.setProperty("value", 32)
        self.fontsize_spinbox.setObjectName("fontsize_spinbox")
        self.horizontalLayout_6.addWidget(self.fontsize_spinbox)
        self.label_2 = QtGui.QLabel(self.burnin_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.fontcolor_combobox = QtGui.QComboBox(self.burnin_groupbox)
        self.fontcolor_combobox.setObjectName("fontcolor_combobox")
        self.fontcolor_combobox.addItem("")
        self.fontcolor_combobox.addItem("")
        self.horizontalLayout_6.addWidget(self.fontcolor_combobox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.burnin_groupbox)
        self.stack_widget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout = QtGui.QGridLayout(self.page_2)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtGui.QSpacerItem(20, 41, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtGui.QLabel(self.page_2)
        self.label_6.setMinimumSize(QtCore.QSize(100, 100))
        self.label_6.setMaximumSize(QtCore.QSize(100, 100))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/tk_nuke_quickreview/complete.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.label_8 = QtGui.QLabel(self.page_2)
        self.label_8.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.jump_to_shotgun = QtGui.QPushButton(self.page_2)
        self.jump_to_shotgun.setObjectName("jump_to_shotgun")
        self.verticalLayout_3.addWidget(self.jump_to_shotgun)
        self.jump_to_panel = QtGui.QPushButton(self.page_2)
        self.jump_to_panel.setObjectName("jump_to_panel")
        self.verticalLayout_3.addWidget(self.jump_to_panel)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(31, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 2, 1, 1, 1)
        self.stack_widget.addWidget(self.page_2)
        self.gridLayout_3.addWidget(self.stack_widget, 0, 0, 1, 1)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem8 = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.cancel = QtGui.QPushButton(Dialog)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_2.addWidget(self.cancel)
        self.submit = QtGui.QPushButton(Dialog)
        self.submit.setObjectName("submit")
        self.horizontalLayout_2.addWidget(self.submit)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.stack_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.description, self.version_name)
        Dialog.setTabOrder(self.version_name, self.start_frame)
        Dialog.setTabOrder(self.start_frame, self.end_frame)
        Dialog.setTabOrder(self.end_frame, self.submit)
        Dialog.setTabOrder(self.submit, self.cancel)
        Dialog.setTabOrder(self.cancel, self.jump_to_panel)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Shotgun Publish", None, QtGui.QApplication.UnicodeUTF8))
        self.version_name_label.setText(QtGui.QApplication.translate("Dialog", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.description_label.setText(QtGui.QApplication.translate("Dialog", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_range.setText(QtGui.QApplication.translate("Dialog", "Frame Range:", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_range_to.setText(QtGui.QApplication.translate("Dialog", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.burnin_groupbox.setTitle(QtGui.QApplication.translate("Dialog", "Render Burn-ins", None, QtGui.QApplication.UnicodeUTF8))
        self.username_checkbox.setText(QtGui.QApplication.translate("Dialog", "User name", None, QtGui.QApplication.UnicodeUTF8))
        self.date_checkbox.setText(QtGui.QApplication.translate("Dialog", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.shotinfo_checkbox.setText(QtGui.QApplication.translate("Dialog", "Shot information", None, QtGui.QApplication.UnicodeUTF8))
        self.frames_checkbox.setText(QtGui.QApplication.translate("Dialog", "Frames", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Font Size", None, QtGui.QApplication.UnicodeUTF8))
        self.fontsize_spinbox.setSuffix(QtGui.QApplication.translate("Dialog", " pt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Font Color", None, QtGui.QApplication.UnicodeUTF8))
        self.fontcolor_combobox.setItemText(0, QtGui.QApplication.translate("Dialog", "White", None, QtGui.QApplication.UnicodeUTF8))
        self.fontcolor_combobox.setItemText(1, QtGui.QApplication.translate("Dialog", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Version Creation Complete!", None, QtGui.QApplication.UnicodeUTF8))
        self.jump_to_shotgun.setText(QtGui.QApplication.translate("Dialog", "Show in Shotgun", None, QtGui.QApplication.UnicodeUTF8))
        self.jump_to_panel.setText(QtGui.QApplication.translate("Dialog", "Show in Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.submit.setText(QtGui.QApplication.translate("Dialog", "Upload to Shotgun", None, QtGui.QApplication.UnicodeUTF8))

from ..qtwidgets import ContextWidget
from . import resources_rc
